### ISSUE TITLE
ModuleNotFoundError: No module named 'third_party.flownet2.networks.resample2d_package'

### ISSUE THREAD

**Issue by TheRustlessSummer** [facebookresearch/consistent_depth#22]
hello, when I run the file 
`python main.py --video_file data/videos/ayush.mp4 --path results/ayush   --camera_params "1671.770118, 540, 960" --camera_model "SIMPLE_PINHOLE"   --make_video`
,there are some errors.
`ModuleNotFoundError: No module named 'networks'`
and
`ModuleNotFoundError: No module named 'third_party.flownet2.networks.resample2d_package'`

errors show in the figure below. But I have install the flownet2.
![图片](https://user-images.githubusercontent.com/48950800/96061816-c10b7880-0ec6-11eb-99e3-5c044964f65b.png)

**Comment by Ahadiandian** [comment]
Have you solve the problem? I also run into the problem that 'resampled2d_package' is not available.
