### ISSUE TITLE
Error when running the demo

### ISSUE THREAD

**Issue by Ahadiandian** [facebookresearch/consistent_depth#24]

**Comment by Ahadiandian** [comment]
Thank you for your great job!
I met some problems  when running the demo, could you please help me find out why

``frame=   92 fps= 35 q=-0.0 Lsize=N/A time=00:00:03.06 bitrate=N/A speed=1.17x    
video:252330kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
ERROR: 92 frames extracted, but 0 PTS entries.`
`

**Comment by aberration213** [comment]
I also ran into the same issue, full log below:
 
Parameters
align: 16
batch_size: 4
camera_model: SIMPLE_PINHOLE
camera_params: 1671.770118, 540, 960
colmap_bin_path: colmap
configure: default
dense_frame_ratio: 0.95
dense_pixel_ratio: 0.3
display_freq: 100
ffmpeg: ffmpeg
flow_checkpoint: FlowNet2
flow_ops: ['hierarchical2']
frame_range: ''
initialize_pose: False
lambda_parameter: 0
lambda_reprojection: 1.0
lambda_view_baseline: 0.1
learning_rate: 0.0004
log_dir: None
make_video: True
matcher: exhaustive
model_type: mc
num_epochs: 20
op: all
optimizer: Adam
overlap_ratio: 0.2
path: results/ayush
print_freq: 1
refine_intrinsics: False
save_epoch_freq: 1
size: 384
sparse: False
val_epoch_freq: 1
video_file: data/videos/ayush.mp4





Processing dataset 'results/ayush'


Output directory: results/ayush\R_hierarchical2_mc

**************************
****  Extracting PTS  ****
**************************
0 frames detected (1080 x 1920).
frames.txt exists, checked OK.

*****************************
****  Extracting frames  ****
*****************************
ffmpeg -i data/videos/ayush.mp4 -start_number 0 -vsync 0 results/ayush/color_full/frame_%06d.png
ffmpeg version 2020-11-29-git-f194cedfe6-essentials_build-www.gyan.dev Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 10.2.0 (Rev5, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-lzma --enable-zlib --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-sdl2 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-libass --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libgme --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libtheora --enable-libvo-amrwbenc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-librubberband
  libavutil      56. 61.100 / 56. 61.100
  libavcodec     58.114.100 / 58.114.100
  libavformat    58. 64.100 / 58. 64.100
  libavdevice    58. 11.103 / 58. 11.103
  libavfilter     7. 91.100 /  7. 91.100
  libswscale      5.  8.100 /  5.  8.100
  libswresample   3.  8.100 /  3.  8.100
  libpostproc    55.  8.100 / 55.  8.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'data/videos/ayush.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.12.100
  Duration: 00:00:03.07, start: 0.000000, bitrate: 137216 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1080x1920 [SAR 1:1 DAR 9:16], 137224 kb/s, 30 fps, 30 tbr, 15360 tbn, 60 tbc (default)
    Metadata:
      handler_name    : VideoHandler
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> png (native))
Press [q] to stop, [?] for help
Output #0, image2, to 'results/ayush/color_full/frame_%06d.png':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.64.100
    Stream #0:0(und): Video: png, rgb24(pc, progressive), 1080x1920 [SAR 1:1 DAR 9:16], q=2-31, 200 kb/s, 30 fps, 30 tbn, 30 tbc (default)
    Metadata:
      handler_name    : VideoHandler
      encoder         : Lavc58.114.100 png
frame=   92 fps= 36 q=-0.0 Lsize=N/A time=00:00:03.06 bitrate=N/A speed=1.19x
video:252330kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
ERROR: 92 frames extracted, but 0 PTS entries.

**Comment by Ahadiandian** [comment]
> I also ran into the same issue, full log below:
> 
> Parameters
> align: 16
> batch_size: 4
> camera_model: SIMPLE_PINHOLE
> camera_params: 1671.770118, 540, 960
> colmap_bin_path: colmap
> configure: default
> dense_frame_ratio: 0.95
> dense_pixel_ratio: 0.3
> display_freq: 100
> ffmpeg: ffmpeg
> flow_checkpoint: FlowNet2
> flow_ops: ['hierarchical2']
> frame_range: ''
> initialize_pose: False
> lambda_parameter: 0
> lambda_reprojection: 1.0
> lambda_view_baseline: 0.1
> learning_rate: 0.0004
> log_dir: None
> make_video: True
> matcher: exhaustive
> model_type: mc
> num_epochs: 20
> op: all
> optimizer: Adam
> overlap_ratio: 0.2
> path: results/ayush
> print_freq: 1
> refine_intrinsics: False
> save_epoch_freq: 1
> size: 384
> sparse: False
> val_epoch_freq: 1
> video_file: data/videos/ayush.mp4
> 
> Processing dataset 'results/ayush'
> 
> Output directory: results/ayush\R_hierarchical2_mc
> 
> **** Extracting PTS ****
> 
> 0 frames detected (1080 x 1920).
> frames.txt exists, checked OK.
> 
> **** Extracting frames ****
> 
> ffmpeg -i data/videos/ayush.mp4 -start_number 0 -vsync 0 results/ayush/color_full/frame_%06d.png
> ffmpeg version 2020-11-29-git-f194cedfe6-essentials_build-www.gyan.dev Copyright (c) 2000-2020 the FFmpeg developers
> built with gcc 10.2.0 (Rev5, Built by MSYS2 project)
> configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-lzma --enable-zlib --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-sdl2 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-libass --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libgme --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libtheora --enable-libvo-amrwbenc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-librubberband
> libavutil 56. 61.100 / 56. 61.100
> libavcodec 58.114.100 / 58.114.100
> libavformat 58. 64.100 / 58. 64.100
> libavdevice 58. 11.103 / 58. 11.103
> libavfilter 7. 91.100 / 7. 91.100
> libswscale 5. 8.100 / 5. 8.100
> libswresample 3. 8.100 / 3. 8.100
> libpostproc 55. 8.100 / 55. 8.100
> Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'data/videos/ayush.mp4':
> Metadata:
> major_brand : isom
> minor_version : 512
> compatible_brands: isomiso2avc1mp41
> encoder : Lavf58.12.100
> Duration: 00:00:03.07, start: 0.000000, bitrate: 137216 kb/s
> Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1080x1920 [SAR 1:1 DAR 9:16], 137224 kb/s, 30 fps, 30 tbr, 15360 tbn, 60 tbc (default)
> Metadata:
> handler_name : VideoHandler
> Stream mapping:
> Stream #0:0 -> #0:0 (h264 (native) -> png (native))
> Press [q] to stop, [?] for help
> Output #0, image2, to 'results/ayush/color_full/frame_%06d.png':
> Metadata:
> major_brand : isom
> minor_version : 512
> compatible_brands: isomiso2avc1mp41
> encoder : Lavf58.64.100
> Stream #0:0(und): Video: png, rgb24(pc, progressive), 1080x1920 [SAR 1:1 DAR 9:16], q=2-31, 200 kb/s, 30 fps, 30 tbn, 30 tbc (default)
> Metadata:
> handler_name : VideoHandler
> encoder : Lavc58.114.100 png
> frame= 92 fps= 36 q=-0.0 Lsize=N/A time=00:00:03.06 bitrate=N/A speed=1.19x
> video:252330kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
> ERROR: 92 frames extracted, but 0 PTS entries.

have you solve the problem?

**Comment by Ahadiandian** [comment]
I have solve the problem. It's because I put some files in the wrong place.

**Comment by aberration213** [comment]
> I have solve the problem. It's because I put some files in the wrong place.

@Ahadiandian What are the files you found in the wrong location? I basically followed the commands in ReadMe but I got the error.

**Comment by Ahadiandian** [comment]
> > I have solve the problem. It's because I put some files in the wrong place.
> 
> @Ahadiandian What are the files you found in the wrong location? I basically followed the commands in ReadMe but I got the error.

extract the file ayush_colmap to the folder resluts/ayush/

**Comment by Yuchen-Song** [comment]
> > > I have solve the problem. It's because I put some files in the wrong place.
> > 
> > 
> > @Ahadiandian What are the files you found in the wrong location? I basically followed the commands in ReadMe but I got the error.
> 
> extract the file ayush_colmap to the folder resluts/ayush/

Hi, I unzipped the file and put it in the correct file folder, but it still doesn't work. Do you have any ideas why does this happen? @Ahadiandian
