### ISSUE TITLE
Running "demo" error

### ISSUE THREAD

**Issue by semel1** [facebookresearch/consistent_depth#44]
Trying to run demo **without** installing **COLMAP**,  following "Quick Start" directions.
After successful subtraction video frames  and creating corresponding subfolders inside result/ayush it throws an error:
"frame=   92 fps= 21 q=-0.0 Lsize=N/A time=00:00:03.06 bitrate=N/A speed=0.711x
video:252330kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
ERROR: 92 frames extracted, but 0 PTS entries." ,
Folder "R_hierarchical2_mc" stays empty.
"ayush_colmap.zip" content extracted to resluts/ayush/
"frames.txt" consists 3 lines: 
0
1080
1920

**Comment by semel1** [comment]
Solved by install "Grep" GnuWin32

**Comment by Yuchen-Song** [comment]
> Solved by install "Grep" GnuWin32

How did you fix that issue? I cannot get the idea QAQ @semel1
