### ISSUE TITLE
Could anyone help me with the two files?

### ISSUE THREAD

**Issue by jesuiskiki** [facebookresearch/consistent_depth#48]
For unknown reason, I cannot download the two files "ayush_color.mp4" and "ayush_colmap.zip".
Could anyone help me with that?
Thanks a lot~

**Comment by jesuiskiki** [comment]
I've got them.

**Comment by Qjizhi** [comment]
> For unknown reason, I cannot download the two files "ayush_color.mp4" and "ayush_colmap.zip". Could anyone help me with that? Thanks a lot~

Hi where is the files, I downloaded it with Error (403), can you share the files?

**Comment by cjlala** [comment]
Hi @jesuiskiki 

Could you please share the ayush_color.mp4? Great thanks.
