### ISSUE TITLE
Support for MobileNetV3 or similar to run on mobile devices

### ISSUE THREAD

**Issue by dblatner** [facebookresearch/consistent_depth#7]
Is it possible to run the model on a mobile device (iOS, Android) or compatible with neural architectures like MobileNetV3, EfficientNet-B0/1/3 ?

I like to see the performance and accuracy in action on real-time captured video streams from the device.

**Comment by roxanneluo** [comment]
Hi, currently the method is offline and is not realtime. To adapt to these models, it won't be too hard to implement an interface similar to [the MiDaS one](https://github.com/facebookresearch/consistent_depth/blob/master/monodepth/midas_v2_model.py) and enable MobileNetV3 as the backend.
