### ISSUE TITLE
pytorch/cuda version

### ISSUE THREAD

**Issue by mattclifford1** [facebookresearch/consistent_depth#8]
I've noticed that pytorch version 1.4 with cuda 10.0 is specified in the requirements (torch==1.4.0+cu100). Is there any specific reason for this requirement or can I run the code with more up to date pytorch and/or cuda? 

Thanks,
Matt

**Comment by miaoqiz** [comment]
I ran into this issue when building "colmap"  -

"
nvcc fatal   : Unsupported gpu architecture 'compute_75'
"

After using a docker container that has cuda-10.0, "colmap" is built correctly. 

Thanks!

**Comment by mattclifford1** [comment]
I've actually found that colmap builds fine with cuda 10.1. However it's important to build with gcc-8 or lower as the build will fail with gcc-9. 

This means changing the code in ./scripts/install_colmap_ubuntu.sh on line 47 from 
`cmake ..`
to
`CC=/usr/bin/gcc-8 CXX=/usr/bin/g++-8 cmake ..`

or substituting version 8 for a lower version depending on your setup.
